print('What is your name?')
name = input()
print('Hello, ' + str(name))
print('What is your age?')
age = int(input())
print('You are ' + str(age) + ' years old')
print('What is your exact height?')
height = float(input())
print('You are ' + str(height) + ' inches tall')